"""empty message

Revision ID: 168154a87353
Revises: 1ecf03e0a48b
Create Date: 2026-02-21 11:16:56.826901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168154a87353'
down_revision: Union[str, Sequence[str], None] = '1ecf03e0a48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_positions_hierarchy_level'), 'manager_positions', ['hierarchy_level'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('in_progress_requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['manager_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_in_progress_requests'), 'managers', ['in_progress_requests'], unique=False)
    op.create_table('manager_skills',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('manager_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_skills')
    op.drop_index(op.f('ix_managers_in_progress_requests'), table_name='managers')
    op.drop_table('managers')
    op.drop_table('skills')
    op.drop_index(op.f('ix_manager_positions_hierarchy_level'), table_name='manager_positions')
    op.drop_table('manager_positions')
    # ### end Alembic commands ###
