"""empty message

Revision ID: 5dfd10c20d22
Revises: 461574bfce5f
Create Date: 2026-02-22 07:11:16.411419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfd10c20d22'
down_revision: Union[str, Sequence[str], None] = '461574bfce5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retries_used',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Integer(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Integer(), nullable=False),
    sa.Column('geo', sa.Integer(), nullable=False),
    sa.Column('image_describe', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_latencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('language', sa.Float(), nullable=False),
    sa.Column('summary', sa.Float(), nullable=False),
    sa.Column('geo', sa.Float(), nullable=False),
    sa.Column('image_describe', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('task_latencies_id', sa.Integer(), nullable=False),
    sa.Column('retries_used_id', sa.Integer(), nullable=False),
    sa.Column('fallbacks_used', sa.JSON(), nullable=False),
    sa.Column('total_processing_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['retries_used_id'], ['retries_used.id'], ),
    sa.ForeignKeyConstraint(['task_latencies_id'], ['task_latencies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_meta')
    op.drop_table('task_latencies')
    op.drop_table('retries_used')
    # ### end Alembic commands ###
