"""empty message

Revision ID: c6c13436447f
Revises: 1052253b8963
Create Date: 2026-02-21 11:18:24.842918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c13436447f'
down_revision: Union[str, Sequence[str], None] = '1052253b8963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['client_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_attachments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'attachment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_attachments')
    op.drop_table('tickets')
    # ### end Alembic commands ###
